In [259]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [267]:
df = pd.read_csv('demand_limpio.csv')
df.columns
df.head(30)

,product_code,warehouse,product_category,date,order_demand,storage,order_Demand,week,month,year
0,Product_0993,Whse_J,Category_028,2012-07-27,100.0,0,100.0,30,7,2012
1,Product_0979,Whse_J,Category_028,2012-01-19,500.0,0,500.0,3,1,2012
2,Product_0979,Whse_J,Category_028,2012-02-03,500.0,0,500.0,5,2,2012
3,Product_0979,Whse_J,Category_028,2012-02-09,500.0,0,500.0,6,2,2012
4,Product_0979,Whse_J,Category_028,2012-03-02,500.0,0,500.0,9,3,2012
5,Product_0979,Whse_J,Category_028,2012-04-19,500.0,0,500.0,16,4,2012
6,Product_0979,Whse_J,Category_028,2012-06-05,500.0,0,500.0,23,6,2012
7,Product_0979,Whse_J,Category_028,2012-06-27,500.0,0,500.0,26,6,2012
8,Product_0979,Whse_J,Category_028,2012-07-23,500.0,0,500.0,30,7,2012
9,Product_0979,Whse_J,Category_028,2012-08-29,500.0,0,500.0,35,8,2012
10,Product_0979,Whse_J,Category_028,2012-09-18,500.0,0,500.0,38,9,2012
11,Product_0979,Whse_J,Category_028,2012-10-11,500.0,0,500.0,41,10,2012
12,Product_0979,Whse_J,Category_028,2012-11-01,500.0,0,500.0,44,11,2012
13,Product_0979,Whse_J,Category_028,2012-11-29,500.0,0,500.0,48,11,2012
14,Product_0979,Whse_J,Category_028,2012-12-26,500.0,0,500.0,52,12,2012
15,Product_1159,Whse_J,Category_006,2012-01-06,50000.0,0,50000.0,1,1,2012
16,Product_1159,Whse_J,Category_006,2012-02-02,50000.0,0,50000.0,5,2,2012
17,Product_1159,Whse_J,Category_006,2012-02-22,50000.0,0,50000.0,8,2,2012
18,Product_1159,Whse_J,Category_006,2012-03-02,50000.0,0,50000.0,9,3,2012
19,Product_1159,Whse_J,Category_006,2012-03-09,50000.0,0,50000.0,10,3,2012
20,Product_1159,Whse_J,Category_006,2012-03-23,50000.0,0,50000.0,12,3,2012
21,Product_1159,Whse_J,Category_006,2012-04-06,50000.0,0,50000.0,14,4,2012
22,Product_1159,Whse_J,Category_006,2012-04-16,50000.0,0,50000.0,16,4,2012
23,Product_1159,Whse_J,Category_006,2012-05-07,50000.0,0,50000.0,19,5,2012
24,Product_1159,Whse_J,Category_006,2012-04-17,50000.0,0,50000.0,16,4,2012
25,Product_1159,Whse_J,Category_006,2012-05-30,50000.0,0,50000.0,22,5,2012
26,Product_1159,Whse_J,Category_006,2012-06-20,50000.0,0,50000.0,25,6,2012
27,Product_1159,Whse_J,Category_006,2012-06-29,50000.0,0,50000.0,26,6,2012
28,Product_1159,Whse_J,Category_006,2012-07-09,50000.0,0,50000.0,28,7,2012
29,Product_1159,Whse_J,Category_006,2012-07-17,50000.0,0,50000.0,29,7,2012

In [268]:
# 2. Convertir los datos a los tipos necesarios
df['date'] = pd.to_datetime(df['date'])
df['order_Demand'] = pd.to_numeric(df['order_demand'], errors='coerce')
# Crear nuevas columnas para la semana, el mes y el año
df['week'] = df['date'].dt.isocalendar().week
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

In [269]:
df['order_Demand'].drop(0, inplace=True)
df.columns

Index(['product_code', 'warehouse', 'product_category', 'date', 'order_demand',
       'storage', 'order_Demand', 'week', 'month', 'year'],
      dtype='object')

002008, 0012,001,0033,0036,0038,0071,0083,0093,0094,0100,0116

In [270]:
l = ["002", "008", "0012", "001", "0033", "0036", "0038", "0071", "0083", "0093", "0094", "0100", "0116"]
df['product_code'] = df['product_code'].apply(lambda x: x.split('_')[1])
df['product_code'] = df['product_code'].apply(lambda x: x if x in l else None)
df = df.dropna()
df['product_code'].head(30)
df.columns
df['product_code'].unique()

array(['0071', '0083', '0033', '0012', '0094', '0036', '0093', '0100',
       '0038', '0116'], dtype=object)

In [272]:
# Cambiar la columna 'date' a tipo datetime df
df['date'] = pd.to_datetime(df['date'])


# Agrupar por 'warehouse', 'product_code', 'year', 'month', 'week', y 'date', y sumar la 'order_demand'
grouped_df = df.groupby(['product_code', 'warehouse', 'year', 'month', 'week', 'date'])['order_demand'].sum().reset_index()

# Ordenar los resultados por 'date' dentro de cada 'warehouse'
grouped_df_sorted = grouped_df.sort_values(by=['product_code', 'date'])

# Crear DataFrames individuales para cada almacén
df_whse_j = grouped_df_sorted[grouped_df_sorted['warehouse'] == 'Whse_J']
df_whse_s = grouped_df_sorted[grouped_df_sorted['warehouse'] == 'Whse_S']
df_whse_c = grouped_df_sorted[grouped_df_sorted['warehouse'] == 'Whse_C']
df_whse_a = grouped_df_sorted[grouped_df_sorted['warehouse'] == 'Whse_A']

In [273]:
df_whse_j.head(30)

    product_code warehouse  year  month  week       date  order_demand
105         0012    Whse_J  2012      1     1 2012-01-05        1000.0
106         0012    Whse_J  2012      1     2 2012-01-10        3000.0
107         0012    Whse_J  2012      1     2 2012-01-11        7000.0
108         0012    Whse_J  2012      1     2 2012-01-12        2000.0
109         0012    Whse_J  2012      1     2 2012-01-13        1000.0
110         0012    Whse_J  2012      1     3 2012-01-16        4000.0
111         0012    Whse_J  2012      1     3 2012-01-17        1000.0
112         0012    Whse_J  2012      1     3 2012-01-19        3000.0
113         0012    Whse_J  2012      1     3 2012-01-20        8000.0
114         0012    Whse_J  2012      1     4 2012-01-24        1000.0
115         0012    Whse_J  2012      1     4 2012-01-25        4000.0
116         0012    Whse_J  2012      1     4 2012-01-27        5000.0
117         0012    Whse_J  2012      1     5 2012-01-31        7000.0
118         0012    Whse_J  2012      2     5 2012-02-01       11000.0
119         0012    Whse_J  2012      2     5 2012-02-03        2000.0
120         0012    Whse_J  2012      2     6 2012-02-07        6000.0
121         0012    Whse_J  2012      2     6 2012-02-09        9000.0
122         0012    Whse_J  2012      2     6 2012-02-10        2000.0
123         0012    Whse_J  2012      2     7 2012-02-13        4000.0
124         0012    Whse_J  2012      2     7 2012-02-15        2000.0
125         0012    Whse_J  2012      2     7 2012-02-17        6000.0
126         0012    Whse_J  2012      2     8 2012-02-22        1000.0
127         0012    Whse_J  2012      2     8 2012-02-23        3000.0
128         0012    Whse_J  2012      2     8 2012-02-24        3000.0
129         0012    Whse_J  2012      2     9 2012-02-28       14000.0
130         0012    Whse_J  2012      2     9 2012-02-29        4000.0
131         0012    Whse_J  2012      3     9 2012-03-01        6000.0
132         0012    Whse_J  2012      3     9 2012-03-02           0.0
133         0012    Whse_J  2012      3    10 2012-03-07        1000.0
134         0012    Whse_J  2012      3    10 2012-03-08        8000.0

In [274]:
df_whse_j.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3832 entries, 105 to 6562
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_code  3832 non-null   object
 1   warehouse     3832 non-null   object
 2   year          3832 non-null   int32
 3   month         3832 non-null   int32
 4   week          3832 non-null   UInt32
 5   date          3832 non-null   datetime64[ns]
 6   order_demand  3832 non-null   float64
dtypes: UInt32(1), datetime64[ns](1), float64(1), int32(2), object(2)
memory usage: 198.3+ KB

In [275]:
grouped_whs_j = df_whse_j.groupby('product_code')

In [276]:
grouped_whs_j = [group for _, group in grouped_whs_j]

In [277]:
grouped_whs_j[0]['product_code'].unique()

array(['0012'], dtype=object)

In [279]:
# Para el almacén 'Whse_S'
grouped_whs_s = df_whse_s.groupby('product_code')
grouped_whs_s = [group for _, group in grouped_whs_s]
print(grouped_whs_s[0]['product_code'].unique())

# Para el almacén 'Whse_C'
df_whse_c.to_csv("whs_c.csv")
grouped_whs_c = df_whse_c.groupby('product_code')
grouped_whs_c = [group for _, group in grouped_whs_c]
print(grouped_whs_c[0]['product_code'].unique())

# Para el almacén 'Whse_A'
grouped_whs_a = df_whse_a.groupby('product_code')
grouped_whs_a = [group for _, group in grouped_whs_a]
print(grouped_whs_a[0]['product_code'].unique())

['0012']
['0012']

IndexError: list index out of range

In [283]:
for group in grouped_whs_a:
    print(group['product_code'].unique())

In [284]:
grouped_whs_c[0]['product_code'].head(30)

0     0012
1     0012
2     0012
3     0012
4     0012
5     0012
6     0012
7     0012
8     0012
9     0012
10    0012
11    0012
12    0012
13    0012
14    0012
15    0012
16    0012
17    0012
18    0012
19    0012
20    0012
21    0012
22    0012
23    0012
24    0012
25    0012
26    0012
27    0012
28    0012
29    0012
Name: product_code, dtype: object

In [ ]:
def me(last_fx: float, last_mu: float, rho=0.8) -> float:
    return rho*last_mu + (1-rho)*last_fx

In [ ]:
grouped_whs_c[0].head(30)

In [286]:
for df_product in grouped_whs_c:
    df_product['storage'] = 0
    df_product['mu'] = 0
    df_product['mu_a'] = 0
    df_product['pi'] = 0
    df_product['pir'] = 0
    
    df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
    cont = 0    
    mu = df_product["order_demand"].mean()
    
    for od in df_product['order_demand']:
        
        df_product['mu'].iloc[cont] = mu
        mu = me(od , mu, rho =0.85)
        mu_a = me(mu, od, rho = 0.85)
        df_product['mu_a'].iloc[cont] = mu_a
        df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
        df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
        
        try:
            df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
        except Exception:
            pass
        
        cont +=1
        df_product.to_csv(f"whs_c_{df_product['product_code'].iloc[0]}.csv")

C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[0] = df_product['order_demand'].iloc[0]*1.3
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu'].iloc[cont] = mu
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['mu_a'].iloc[cont] = mu_a
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pi'].iloc[cont] = abs(df_product["storage"].iloc[cont] -mu - od)
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['pir'].iloc[cont] = df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_product['storage'].iloc[cont+1] = df_product['storage'].iloc[cont] - df_product['order_demand'].iloc[cont] + df_product['pi'].iloc[cont]
C:\Users\jesus\AppData\Local\Temp\ipykernel_3676\2835895244.py:8: SettingWithCopyWarning:

In [ ]:
grouped_whs_c[0].columns

In [ ]:
grouped_whs_c[2].head(50)

In [ ]:
len(grouped_whs_c)
for grp in grouped_whs_c: